### ISSUE TITLE
Can't make it work in Manjaro!

### ISSUE THREAD

**Issue by gvasco** [blipk/Customised-Workspaces#10]
Hi! I've been trying to get your plugin to work on Manjaro but so far no luck. I've tried downloading from the gnome extensions website as well as github directly, tried switching off every other extension to see if some other extension was causing issues and nothing has worked so far. No matter what I do the switch is always faded (screenshot) and I see no changes on the GUI. Would love to try your extension so any help is much appreciated.

![Screenshot from 2020-11-03 23-53-59](https://user-images.githubusercontent.com/6905698/98049489-15ec4000-1e30-11eb-955c-046a14249497.png)

**Comment by blipk** [comment]
Hi @gvasco I was having a similar issue trying to enable it via tweaks and it worked with the Extensions app, however it looks like you are using that but I'm not certain from your screenshot.

The gnome-tweaks app hasn't been updated in some versions and it will not enable some extensions, please install the Extensions app if you are not using it.

If you are using the Extensions app and not gnome-tweaks, could you provide some more info:
What gnome-shell version are you using?

Do you have a ~/.config/worksets@blipk.xyz/debug.log file? Or the folder at least?

Can you check in looking glass extensions for errors? (Alt+F2 -> 'lg' then go to Extensions tab and 'Show Errors' for the extension)

Can you check gnome-logs for errors? (search for 'extensions' or 'worksets')

Thanks.

**Comment by gvasco** [comment]
Thank you for the fast reply!

I was using both extensions and tweaks, tried initially to uninstall tweaks but nothing changed.

I had a look arround after your reccomendations but unfortunately the install would fail and there was no log folder (gnome extensions show output bellow). I found out (new to gnome) about looking glass for debug info on extensions and it showed I was missing libwnck needed by the plugin, got that installed and the addon  now seems to be working.
