### ISSUE TITLE
Is there a way to trigger mounting/dismounting desktops with a command from terminal?

### ISSUE THREAD

**Issue by georgesoteriou** [blipk/Customised-Workspaces#11]
I want to add keyboard shortcuts to mount a specific desktop. A CLI would make this easy to do.

**Comment by blipk** [comment]
There is no CLI support and it is not planned.
I would welcome a PR it shouldn't be too difficult but I don't have the time right now.
If you would like me to guide you on how to implement it let me know.

**Comment by blipk** [comment]
Hi @georgesoteriou 

I found a solution that may work for you, you can use dbus calls to call any function in the extension code e.g.:
`dbus-send --session --type=method_call --dest=org.gnome.Shell /org/gnome/Shell org.gnome.Shell.Eval string:'Main.extensionManager.lookup("worksets@blipk.xyz").workspaceManager.switchToWorkspace(1);'`

For your use:
`dbus-send --session --type=method_call --dest=org.gnome.Shell /org/gnome/Shell org.gnome.Shell.Eval string:'let x = Main.extensionManager.lookup("worksets@blipk.xyz"); x.session.displayWorkset(x.session.Worksets[1]);'`
