### ISSUE TITLE
Suggestion: Allow to disable environments

### ISSUE THREAD

**Issue by ruffson** [blipk/Customised-Workspaces#12]
Hi there, thank you for all the work you have put in this!
I installed this extension because of one thing only: isolated workspaces.
Since the only other extension that does this is abandoned, I switched over to this one.

And because I do not need and want any of the other features and complexity that this extension adds, I would like an option in the extension to really disable anything but the isolation. 

However currently when I deselect every other feature besides the isolated applications I still see:
 - overlay icons on the little workspace previews in the `Activities` overview
 - when switching workspaces from the `Activities` overview, the windows in the little workspace preview fade in and out

And in general it would just be nice if unwanted features would not use up resources unnecessarily of course.

So if you could add an option "disable environments" or however this should be called, which would disable every feature besides isolated workspaces, that would be very much appreciated!
Thanks again for the great effort!

**Comment by blipk** [comment]
Hi @ruffson 

This is how it's intended to behave when you have those settings disabled, unfortunately there was a bug. I've pushed a quick fix that will remove the icons from the workspace panel in the activities overview.

As for the windows fading in and out, I'm not sure whats causing that and will have to dig a little deeper when I have some time, hopefully it's not too much of an issue for you right now.

You can clone the repo here and use the install script or just extract the zip over the current extension installation.

Let me know if that helps.

Thanks.

**Comment by ruffson** [comment]
Thank you for this, I will try it out!
