### ISSUE TITLE
Dismiss Notifications on Right Click

### ISSUE THREAD

**Issue by ivanmood0** [blipk/Customised-Workspaces#14]
Since I did not find branch for extension "Dismiss Notifications on Right Click", I will write here. After right-clicking, all subsequent notifications are no longer displayed.

**Comment by blipk** [comment]
I'm not experiencing this issue.

Can you provide some details on your system and gnome-shell version?
Notifications from which application?
Have you tried with only this extension enabled?

**Comment by blipk** [comment]
I used this page to test chrome notifications which are managed by the gnome-shell notification system:
https://www.bennish.net/web-notifications.html

I can pop and right click as many as I'd like.

**Comment by ivanmood0** [comment]
> I'm not experiencing this issue.
> 
> Can you provide some details on your system and gnome-shell version?
> Notifications from which application?
> Have you tried with only this extension enabled?

Mostly (during the period of use) I noticed such behavior in the deb version of Telegram, although this also happened with notifications from Geary email client. I mean that after right-clicking on a pop-up window from a program, subsequent messages (not queues or groups) from the same program, ie after a few minutes, etc., are no longer displayed in the pop-up window, but only the notification sound is played. I understand that the main idea of ​​the extension was to minimize notifications (for later viewing), without deleting (without closing) them in the notification menu itself, so as not to forget about them.

If I disable this extension and restart the gnome shell or log out-in, the notifications are displayed correctly, regardless of whether I close them or do not respond at all, and wait until they themselves disappear.

Ubuntu 20.04
Gnome 3.36

**Comment by blipk** [comment]
I don't really use the notifications much, they mostly get in my way, so it was just a simple extension to get rid of them.

I tried some other exit conditions, hovering the notification or clicking the exit button, and each has the same behaviour I implemented, it will dismiss all queued notification banners as well as all in the dash menu for that application.

The only way the notification will remain in the dash menu is if you simply let it timeout.

I looked at achieving this same (as timeout) behaviour on right click, however the gnome-shell implementation is very complicated and split over events and inherited classes 5+ source files, and seems it would require a lot of injections into that code.

Perhaps when they simplify this system in a later version it may be easier to implement, or you can have a look at the TODO section in the updated code and try it for yourself.

I created a new repository here if you would like to open a new issue:
https://github.com/blipk/Dismiss-Notifications
