### ISSUE TITLE
Wallpaper not showing in workspace thumbnail

### ISSUE THREAD

**Issue by andregalastri** [blipk/Customised-Workspaces#15]
Distro: Ubuntu 20.04
No other extension enabled.

## Explanation
Hello! The workspace thumbnails shows the windows, but the background is black, without the wallpaper.
![image](https://user-images.githubusercontent.com/49572917/113358003-5c7c9280-931b-11eb-8179-1aadb33b7ba6.png)

**Comment by blipk** [comment]
Hi @andregalastri 

Can you provide your gnome-shell version and which version of the extension?
Can you also upload session.json and debug.log from  ~/.config/worksets@blipk.xyz

Thanks.

**Comment by andregalastri** [comment]
Gnome Shell 3.36.4
![image](https://user-images.githubusercontent.com/49572917/113370860-4f6f9b80-933b-11eb-8414-942e30481162.png)

Extension version: 16
![image](https://user-images.githubusercontent.com/49572917/113370830-441c7000-933b-11eb-8f2b-d42b554795f3.png)

Debug.log and session.json files
[logs.zip](https://github.com/blipk/Customised-Workspaces/files/6247206/logs.zip)

**Comment by blipk** [comment]
Thanks @andregalastri 
I'm looking into it now, there's an error creating the pixel bufer from the file you're using.
Can you provide your desktop wallpaper as well?

**Comment by andregalastri** [comment]
Sure. Here it is

[Wallpaper nasa-rTZW4f02zY8-unsplash.zip](https://github.com/blipk/Customised-Workspaces/files/6247227/Wallpaper.nasa-rTZW4f02zY8-unsplash.zip)

Thanks

**Comment by blipk** [comment]
Thank @andregalastri 
I'm not sure what the pixel buffer error was, it was related to the background rendering in the menu not the overview, you may have had it set to a file that was moved at some point?

Anyway, I had another issue with this recently that I had fixed, but I didn't push the update to the gnome extension site for older versions of gnome-shell.

I've pushed the updates here, if you could test that for me using the zip extension archive from github and if it works I will upload to the extension site :)

**Comment by andregalastri** [comment]
![image](https://user-images.githubusercontent.com/49572917/113375080-0cb2c100-9345-11eb-9b7b-f19185c77d5d.png)
Installed the version of the zip file and it seems to solve the problem

But now this icons here are wrongly positioned. It's a minor bug, however.
![image](https://user-images.githubusercontent.com/49572917/113375757-78e1f480-9346-11eb-9382-83cea74c8e7f.png)

**Comment by blipk** [comment]
Obrigado @andregalastri
Good to know that is fixed.

I'm not sure what you mean with the icons, their was some UI changes in the 3.38 version, those icons are for choosing the background view mode, it should show your background image in that empty area though, could you upload your debug.log file again?

Also I notice the other latest screenshot, it's not showing the icons in the overview thumbnails, did you disable the "Show workspace overlay" option? The debug file may help.

**Comment by andregalastri** [comment]
Hello!
I though the icon position were strange just because this empty area, but if it is supposed to show the wallpaper there, now the icon position makes sense

Here it is the logs
[logs.zip](https://github.com/blipk/Customised-Workspaces/files/6249379/logs.zip)

About the icons in thumbnails, yes, I did disable the "Show workspace overlay"

**Comment by blipk** [comment]
Hmm. Thanks andre.

I'm not sure whats causing that pixel buffer error on rendering the wallpaper image there, I have tried your config file with your wallpaper file and it works fine for me, perhaps because its a large file maybe your system is running out of memory? Or it may be a random bug with something else in your system configuration.

If you would like me to look into it, could you delete your configuration and debug file and try again with the latest version from github.

Otherwise, feel free to close this issue.
Thanks again for the detailed report and responsive answers.

**Comment by andregalastri** [comment]
Right, I will close the issue.

I don't know if it is relevant, but I use ultrawide monitor, 2560x1080 (21:9) at 75MHz refresh rate. Does it have something with it?

And I will leave my specs, if it is useful:
Processor: Intel i3-9350KF 4.00GHz
Graphics Card: Nvidia GeForce GTX 750ti 
Memory: 1x 16GB
SSD Kingston V300 120GB

Thanks for the support and for this great extension!
