### ISSUE TITLE
Background change not reflected in Gnome-Workspace indicator

### ISSUE THREAD

**Issue by THgithub19** [blipk/Customised-Workspaces#16]
**Please disable all other extensions and see if the issue persists**
Done (after screenshots), issue persists

**Please include the debug file from ~/.config/worksets@blipk.xyz/debug.log**
[debug.log](https://github.com/blipk/Customised-Workspaces/files/6264392/debug.log)

**Desktop (please complete the following information):**
 - Gnome-Shell Version: 3.36
 - Extension Version [e.g. 22]: 22
 - Ubuntu Standard 20.04

**Describe the bug**
I have changed the background images of all four configured workspaces, but when I press Super key the panel on the right side does show the background of the current workspace four times. Additionaly, unlike in the animated image on usage, the workspaces are not labeled in the overview panel.

**To Reproduce**
1. Press Super key
2. See images in Workspace overview panel

**Expected behavior**
I expect to see each workspace with its own background in the overview panel and its label, as shown in the animated image on usage [https://extensions.gnome.org/extension/1583/worksets/](url)

**Screenshots**
Attached two screenshots of two different workspaces which illustrate the issue:
![Workspace_3](https://user-images.githubusercontent.com/62480388/113707448-37ec3600-96e0-11eb-93f4-79b6b5da1160.png)
![Workspace_4](https://user-images.githubusercontent.com/62480388/113707480-3fabda80-96e0-11eb-8fd6-af8c9666a0ff.png)

**Comment by blipk** [comment]
This has been fixed in newer versions.
Please use the GitHub release or wait for the updates to be approved on the extensions website.

**Comment by blipk** [comment]
Actually, this looks like another issue, apologies.
I kind of messed up, there has been so many breaking changes with each gnome-shell version lately, I tried to keep my extension compatible with all of them but seems I failed. Will likely just have version specific versions from now on.

If you could try using the latest commit from here and let me know if that fixes it for you.

Thank you.

**Comment by blipk** [comment]
Latest release on gnome extensions should fix this.

**Comment by THgithub19** [comment]
@blipk 
Thank you for your quick response. I updated using the green extensions update button, but now I just get a red error button. I cant even reinstall the old working extensions version 22. I suppose there are some files around or cached things that prevent reinstallation. I removed .config/worksets.blipk.xyz and .local/share/gnome-shell/extensions/worksets.blipk.xyz, but reinstallation still does not work.
However, the extension is very promising, I just want to have clearly distinguishable and seperately configurable workspaces like in CDE 25 years ago, but more modern looking like in Gnome, and this is exactly what your extension provides. Therefore a big thank you for your work!

**Comment by blipk** [comment]
Thanks @THgithub19 
Could you let me know which version you downloaded? 26?
Are you using gnome tweaks or gnome extensions to enable the extension? The tweaks app has some D-Bus issues and sometimes will not enable extensions, it has been deprecated and now the Extensions app is reccomended.

You could try the latest developing package here (v27): https://github.com/blipk/Customised-Workspaces/blob/master/worksets%40blipk.xyz.zip
Delete your current installation in ~/.local/share/gnome-shell/extensions/worksets@blipk.xyz and use the zip contents.

If that doesn't fix your issue, please also upload your new debug.log file.
If there is no debug file, look for an error message in 
- the gnome Extension app when expanding the Customised Workspaces extension, 
- In 'looking glass' under the 'Extensions' tab (Alt+F2 then type 'lg')
- Or in the gnome-logs app searching for 'ERROR' or 'workset'

Thanks for your feedback and I'd be happy to fix the issue for you.

**Comment by THgithub19** [comment]
Great, your updated package v27 solves the issue, now it shows the different wallpapers and the labels for quick orientation! After deleting my installation attempt I put the zip-contents into the directory you said, restarted the gnome shell and then it worked. I sent you a beer per paypal, as it was AUD it goes down under, I reckon - cheers mate!

**Comment by blipk** [comment]
Thanks a lot @THgithub19 
Great to know everythings working and that you're liking the extension :) 
Appreciate the beer money too, thank you.

If you have any more issues, or if you'd like to request any features, feel free to open another issue here.
Take care.

**Comment by THgithub19** [comment]
The latest upgrade (v27 -> v29) does not work here on Ubuntu 20.04 with Gnome 3.36.8, I am afraid to tell. Reverting to v27 restores my workspace configuration. As there seems to be no way to avoid updates for shell extensions apart from workarounds, I will get the corresponding error message next time I log in and post it then.
