### ISSUE TITLE
gnome 3.38 issues

### ISSUE THREAD

**Issue by smalltimer** [blipk/Customised-Workspaces#19]
Hi, 
Thank you for making this gnome-extension available to the common public. 

I am trying to install it in a Debian 11 system with gnome shell 3.38.1. I have also installed libwnck22 and libwnck-3-0 from the debian repositories. However, the extension fails to run. Am I missing something here? 

Cheers!

**Comment by blipk** [comment]
Hi @smalltimer 
Can you provide an update if you got this working?
I was trying to make a version that was compatible with 40 and pre40 but it proved problematic, you might want to try an older version of the extension.

Please repost as another issue using the template if you are still having problems.
