### ISSUE TITLE
Wallpaper in desktop thumbnail is different from the actual desktop wallpaper

### ISSUE THREAD

**Issue by SilverLuke** [blipk/Customised-Workspaces#20]
I am using the nasa-apod (https://extensions.gnome.org/extension/1202/nasa-apod/) extension to manage the desktop background but when I go in activity screen (press the super/win/meta key) I get a different background image in the thumbnail. The background image in the thumbnail is actually the image that was my background when i have installed your extension.
I have tried the "disable wallpaper management" options with no luck.

My system:
 - Gnome-Shell Version (gnome-shell --version): GNOME Shell 40.4
 - GJS Version (gjs --version): gjs 1.68.3
 - Extension Version [e.g. 22]: 40.beta 30
 - Linux distribution and version: 5.14.2-1-MANJARO x86_64

**Comment by blipk** [comment]
Does the issue persist if you disable nasa-apod?
Could you also check if it persists if you use the 'Disable Wallpaper Management' option?

Cheers.

**Comment by blipk** [comment]
@SilverLuke 
I have pushed some updates that are live on github, and will be on extensions.gnome.org soon enough.
Can you let me know if you are still having this issue after testing v37 of the extension.

**Comment by blipk** [comment]
Okay, this is a problem I've known and been trying to fix it. The thumbnails will be accurate when the overview is first opened, but can get chopped up and blanked out when changing workspace settings.

I don't really use this extension anymore, and a large extension to how gnome-shell handles backgrounds for multiple workspaces really needs to be implemented, right now it is just a display hack.

I can add an option to keep them blank like gnome 41 default, or put the custom workspace name in them, if anyone would prefer any of those options for the time being.

**Comment by SilverLuke** [comment]
Now I can't start the extension. This is the log when I try to open the settings :
```
ImportError: No JS module 'ui' found in search path
Stack trace:
@/home/luke/.local/share/gnome-shell/extensions/worksets@blipk.xyz/utils.js:180:108
@/home/luke/.local/share/gnome-shell/extensions/worksets@blipk.xyz/dev.js:29:30
@/home/luke/.local/share/gnome-shell/extensions/worksets@blipk.xyz/prefs.js:33:17
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:206:33
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```
I am using the git version

**Comment by blipk** [comment]
Thanks @SilverLuke 
This has been fixed in the latest git build.
There is nothing in the extension preferences anyway, it is all in the menu from the dash/panel indicator icon.

**Comment by SilverLuke** [comment]
Now works as expected for me.
Thanks for the time you put in, I will close this issue. 
In my opinion you should move the configuration "pop-over" in the configuration window.

**Comment by blipk** [comment]
Thanks @SilverLuke 
The extension preferences window uses a different UI toolkit, GTK, whereas everything else in the gnome-shell UI uses "shell toolkit", I prefer to keep everything consistent.

The idea is to set it up from the indicator to your liking and then toggle off 'Show panel indicator' in the 'Extension Options' therein.

If you want to change the 'Extension Options' again, the dash/panel icon will reappear if you click the configuration cog button in the Gnome Extensions app, or there will also be a button to do so in the overview overlay if that is enabled.
