### ISSUE TITLE
[Feature] update extension for GNOME 41

### ISSUE THREAD

**Issue by khimaros** [blipk/Customised-Workspaces#21]
**Is your feature request related to a problem? Please describe.**
this extension cannot be installed from extensions.gnome.org on GNOME 41

**Describe the solution you'd like**
it might be as simple as adding `"41"` to the list here: https://github.com/blipk/Customised-Workspaces/blob/master/worksets%40blipk.xyz/metadata.json#L15

there may be other incompatibilities, but this would be a good place to start.

**Comment by blipk** [comment]
Thanks @khimaros  have added support along with some other features, has not been tested personally (not yet on my distro), but I will close this and take your word, any specific bugs can be brought up as new issues.
