### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by tsphill** [blipk/Customised-Workspaces#23]
Unable to select Done on  "Please enter name new custom workspace"

**Comment by blipk** [comment]
Hi @tsphill please repost this using the bug report template: https://github.com/blipk/Customised-Workspaces/issues/new?assignees=blipk&labels=bug&template=bug_report.md&title=%5BBug%5D

Fill in as much of the information as possible. I can't do anything without knowing the details of your system.

A screenshot would be useful as well.
