### ISSUE TITLE
Unable to create new environment [Bug]

### ISSUE THREAD

**Issue by phillw** [blipk/Customised-Workspaces#24]
- Gnome-Shell Version (gnome-shell --version): 40.4.0
 - GJS Version (gjs --version): 1.68.3
 - Extension Version [e.g. 22]:
 - Linux distribution and version: arch latest

Unable to select Done on "Please enter name for new custom workspace"

**To Reproduce**
1. Select "New Enviroment"
2. Enter name
3. Unable to select Done, able to select Cancel

[debug.log](https://github.com/blipk/Customised-Workspaces/files/7479142/debug.log)
![Screenshot from 2021-11-04 15-59-39](https://user-images.githubusercontent.com/5846516/140426322-e4840945-b91b-4300-9ac7-6c909663b80d.png)

**Comment by blipk** [comment]
Thanks @phillw 

Can you check if you have a `~/.config/worksets@blipk.xyz/session.json` file and share that too if you do.

Looks like it either doesn't exist or is corrupted, this should be handled in the extension though.

After sharing it, you can try deleting it and restarting the extension and that might fix it, I'd like to see to prevent this in the future though.

**Comment by phillw** [comment]
[session.txt](https://github.com/blipk/Customised-Workspaces/files/7480123/session.txt)

**Comment by blipk** [comment]
Hi @phillw 
Did you rename that? It should be .json
Does deleting it and restarting the extension fix the issue?

What version of the extension are you using? It doesn't look right, there should be a `Worksets: []` subobject that should have been generated on first run.

Disable the extension, delete session.json, then enable the extension. You should be fine after that.

**Comment by phillw** [comment]
Yes renamed it to upload.
Installed version from gnome extensions & git - same error.

**Comment by blipk** [comment]
> Disable the extension, delete session.json, then enable the extension. You should be fine after that.

Reinstalling the extension won't delete the configuration and debug files.

**Comment by blipk** [comment]
Thanks @phillw 
I assume that fixed your issue.
Not sure how it got broken, will look into rebuilding the session on those errors in the future.
Will close this issue, but feel free to comment and tag me if it still persists.

**Comment by phillw** [comment]
Yes this fixed it thank you.

Based on the screenshots in readme I think I am missing window management features - I have not actually used this plugin on lower versions of gnome, however, I don't think it is functioning as intended.
I make an enviroment, the windows do not save/reload when activating the enviroment.
