### ISSUE TITLE
Configuration cannot be opened after installation

### ISSUE THREAD

**Issue by phiroict** [blipk/Customised-Workspaces#25]
On opening the configuration file the screen opens with an error : `Something's gone wrong`: 

Technical error: 
The settings of extension worksets@blipk.xyz had an error:
```
ImportError: No JS module 'ui' found in search path
```

Stack trace:
```
@/home/phiro/.local/share/gnome-shell/extensions/worksets@blipk.xyz/utils.js:180:108
@/home/phiro/.local/share/gnome-shell/extensions/worksets@blipk.xyz/dev.js:29:30
@/home/phiro/.local/share/gnome-shell/extensions/worksets@blipk.xyz/prefs.js:33:17
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:206:33
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Please disable all other extensions and see if the issue persists**
No difference

**Please include the debug file from ~/.config/worksets@blipk.xyz/debug.log**
(worksets@blipk.xyz) [8/11/2021, 11:00:14 am]::Info    | cw-shell-extension.init | @```````````````````````````````````|
(worksets@blipk.xyz) [8/11/2021, 11:00:14 am]::Info    | cw-shell-extension.enable | @---------------------------------|
(worksets@blipk.xyz) [8/11/2021, 11:00:14 am]::Info    | cw-shell-extension.enable | @~................................|

**Desktop (please complete the following information):**
 - Gnome-Shell Version (gnome-shell --version): GNOME Shell 40.5
 - GJS Version (gjs --version): gjs 1.68.3
 - Extension Version [e.g. 22]: latest (not selected)
 - Linux distribution and version: Endeavor OS latest version (rolling Arch) 

**Describe the bug**
Installation of the extension successful, the current running application is in the top left of the bar. When selecting the configuration button from the gnome-extension site for the plugin the error occurs 

**To Reproduce**
1. Install pluyin
2. Click on configuration button on the webpage of the extensions 
3. Error occurs
**Expected behavior**
The configuration panel should open with the configuration items 

**Screenshots**
If applicable, add screenshots to help explain your problem
![Screenshot from 2021-11-08 11-10-07](https://user-images.githubusercontent.com/3645795/140663594-887b96a2-918f-4579-ac79-3337f8dd15d7.png)
.

**Comment by blipk** [comment]
Thanks for the report @phiroict 
This has been fixed with the latest github build, will be pushed in the next version to gnome extensions.

There is nothing in there anyway, it just opens the panel indicator icon in case it was accidentally disabled.
All the settings and options are in there.
