### ISSUE TITLE
Can't Edit Apps Shown on Dock

### ISSUE THREAD

**Issue by RyanRix** [blipk/Customised-Workspaces#26]
**Please disable all other extensions and see if the issue persists** Yes

**Please include the debug file from ~/.config/worksets@blipk.xyz/debug.log** 
[debug.log](https://github.com/blipk/Customised-Workspaces/files/7803267/debug.log)

**Desktop (please complete the following information):**
 - Gnome-Shell Version (gnome-shell --version): 40.5
 - GJS Version (gjs --version): 1.68.4
 - Extension Version [e.g. 22]: Current
 - Linux distribution and version: Ubuntu 21.10

**Describe the bug**
When displaying settings, where the apps on the dock should be shown, instead is shown: "Nothing here!"

**To Reproduce**
1. Go to '...'  Settings, 
2. no apps are shown
3. click on a workspace
4. 3. message shows "Nothing here!"

**Expected behavior**
When I installed, and for a day or so afterwards, it would show the current favourites on the dock, and allow them to be toggled on or off. Now no favourites are shown, just the 'Nothing here!2 message.

**Screenshots**
![Screenshot from 2022-01-03 17-27-47](https://user-images.githubusercontent.com/49094556/147962162-df340968-47f5-44c4-9f10-915b80354844.png)

I should add - this extension is great, and just what I wanted. I hope the error is mine and easily fixed.

**Comment by blipk** [comment]
Hi @RyanRix 
If you have the "Disable wallpaper management" and "Hide favourites in details" enabled in the "Extension Options" naturally there will be nothing to show there.

Can you confirm whether you have both of these enabled?

If you don't, can you please upload your ~/.config/worksets@blipk.xyz/session.json file as well.

**Comment by RyanRix** [comment]
I am an idiot! You are right - I had "Hide favourites in details" enabled in the "Extension Options". I really must learn to read.

Thanks for showing me the error of my ways, and for a great extension!

Ryan
