### ISSUE TITLE
[Bug] Cannot switch back into showing apps from all workspaces on the dock

### ISSUE THREAD

**Issue by John15321** [blipk/Customised-Workspaces#29]
**Also try deleting your session configuration file and restarting (~/.config/worksets@blipk.xyz/session.json)**
I uninstalled the whole extension and deleted the whole directory but it didn't help (I also restarted)

**Please include the debug file from ~/.config/worksets@blipk.xyz/debug.log**
well too late I don't have it

**Also include your session configuration file from ~/.config/worksets@blipk.xyz/session.json**
well too late I don't have it

**Desktop (please complete the following information):**
 - Gnome-Shell Version (gnome-shell --version): GNOME Shell 40.5
 - GJS Version (gjs --version): gjs 1.68.4
 - Extension Version [e.g. 22]:
 the latest one from here
 https://extensions.gnome.org/extension/1583/worksets/
 - Linux distribution and version: PopOS
```text
Linux pop-os 5.15.15-76051515-generic
PopOS 21.10
```
I have the COSMIC desktop

**Describe the bug**
After installing the extension I didn't really bother doing anything and I uninstalled it in a second. But it has changed my desktop settings so that I cannot see apps from different workspaces in my dock even tho I have uninstalled the extension

**To Reproduce**
Install the extension
Uninstall the extension
The apps from different workspaces will not be seen

**Expected behavior**
Should revert to the state from before the extensions installation and show apps from all worksapces or whatever was configured

**Comment by John15321** [comment]
I found this StackOverflow post:
https://askubuntu.com/questions/992558/how-can-i-configure-the-ubuntu-dock-to-show-windows-only-from-the-current-worksp

I did the reverse and set the flag to `false`
this fixed the issue, but could you please fix it so that the extension does not bring changes that have to be fixed thru a command line?

```bash
gsettings set org.gnome.shell.extensions.dash-to-dock isolate-workspaces true
```

**Comment by blipk** [comment]
That shouldn't have fixed the issue as you are setting dash-to-dock settings there.

Do you have that installed?

My extension has to sync its settings with dash-to-dock and dash-to-panel, otherwise they will fight over what they want to render on each workspace.

You will have to disable the setting in my extension before uninstalling, as it is enabled by default, I could make it check the other extension settings too, if thats the issue you're having.

**Comment by blipk** [comment]
Hi @John15321 
Can you confirm the details of the bug I requested?

**Comment by blipk** [comment]
closing due to lack of response
