### ISSUE TITLE
No longer works on 3.22

### ISSUE THREAD

**Issue by taciturasa** [blipk/Customised-Workspaces#3]
GNOME being as descriptive as it is, it simply just errors on the webpage and can't initialize in Tweaks. Not sure what logs there are, so let me know what you need.

**Comment by blipk** [comment]
Hi, If you are still interested, I am updating this extension now.
Let me know and I can send you an updated debug build

**Comment by blipk** [comment]
This should be resolved. 
There are logs in ~/.config/worksets@blipk.xyz if you are still having issues.
