### ISSUE TITLE
Add Support for Gnome 43

### ISSUE THREAD

**Issue by rclabough** [blipk/Customised-Workspaces#32]
Gnome 43 is now the default Gnome with Ubuntu, and unfortunately has broken Customized Workspaces.

I've tried manually upping the version in the json to support 43, but on flipping workspaces it will set my background image, then set it immediately back to the default.  I have suspicions that this is due to the new Dark Mode in 43.

**Comment by blipk** [comment]
Hi @rclabough 

I won't be able to work on this until it arrives on Arch.

If you can share your files from ~/.config/worksets@blipk.xyz I could possibly offer a temporary fix.

**Comment by blipk** [comment]
Hey @rclabough 

I was having some trouble with the dark mode in shell version 42.1 on my distro too.
I have pushed some updates to this repo to handle selecting different backgrounds for dark mode and light mode for each workset.

Are you able to confirm this is working on shell version 43 as well? You can use the zip file from the repository.

**Comment by blipk** [comment]
Closing due to no response, and have pushed updates that should handle dark mode in 43.

If anyone else has specific issues with 43 or anything, please open another issue with some specific information.

**Comment by rclabough** [comment]
I'm so sorry, I don't have notifications on and _completely_ forgot about this.  My bad, thank you for even still looking into the issue.

For what it's worth, I checked out the change and you did fix it!  Dark mode appears to be working again in Gnome 43!

**Comment by blipk** [comment]
Thanks for confirming that @rclabough 
You should be able to set a different wallpaper for either light or dark mode as well.
Hope you enjoy the extension :)
