### ISSUE TITLE
[ARCH] [DOC] Use libwnck3 instead libwnck

### ISSUE THREAD

**Issue by cristomc** [blipk/Customised-Workspaces#33]
Hi! I just installed the extension on my Arch, but as I was following the README, I had issues making it working with the `libwnck`. Instead for Arch distros we should use libwnck3 (Extra repository). I think it would be nice to add it in the readme.

Good work by the way! :)

**Comment by blipk** [comment]
Thanks @cristomc 

I'm using an Arch derivative and did not require specifically installing any packages, although I understand base Arch may be different.

I don't think this is really an issue as libwnck is the generic name of the library, and would be too much for me to list the package name for every distro.
It's good you posted this issue though, as others can search if they are having trouble finding the correct package for their distro.

Also, glad you're enjoying the extension, I put a lot of work into it and don't exactly get paid, so it's always nice to know it's being appreciated.

**Comment by blipk** [comment]
I'm actually not sure if Wnck is required anymore, I think it was a very early version using it.
I will look into removing the dependency in the next version.
