### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by gmejzej** [blipk/Customised-Workspaces#34]
**Please disable all other extensions and see if the issue persists**

**Also try deleting your session configuration file and restarting (~/.config/worksets@blipk.xyz/session.json)**

**Please include the debug file from ~/.config/worksets@blipk.xyz/debug.log**

**Also include your session configuration file from ~/.config/worksets@blipk.xyz/session.json**

**Desktop (please complete the following information):**
 - Gnome-Shell Version (gnome-shell --version): 42.4
 - GJS Version (gjs --version): 1.72.2
 - Extension Version [e.g. 22]: how do I identify what version is installed? I installed extension on 2022-09-07
 - Linux distribution and version: Fedora 36 workstation (same issue on Debian 11)

**Describe the bug**
text documents are not isolated to one workspace unlike behavior of every other app/document

**To Reproduce**
1) open a gedit or text-editor document in workspace-1.
2) move to workspace-2 and using FILES app, open a gedit or text-editor file.
3) upon opening, Gnome moves me to workspace-1's gedit/text-editor (i.e., it didn't open the document in workspace-2)
4) This is unlike what happens if I were to open .pdf, web-browser, FILES app, .png, .jpg, .ods, etc. (i.e., while in workspace-2, if I were to open a .pdf or .png, etc, it would open in workspace-2)

**Expected behavior**
Like every other app/document, when opening gedit/text-editor document in workspace-2, it should open in workspace-2 and not take me to workspace-1

**Screenshots**

**Comment by blipk** [comment]
Hi @gmejzej 
This extension uses the same workspace isolater as dash-to-panel and other extensions in the marketplace, this is more a problem with gnome and how the WM stack works, applications can choose how they work with xdg-open and the rest of the spec.

This is gedits developers intended behaviour, it opens any document in an already opened window, not a new one.

If you want to change that behaviour, you will have to look for another solution, perhaps another .desktop file with different args.
