### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by reecebower98** [blipk/Customised-Workspaces#35]
im running debian 11. after installation when trying to select an opened program on my panel "dash to panel" my system froze. after shut down, i could not log in upon first try. id than get an error screen and log in with extensions disabled.

**Comment by blipk** [comment]
Hi @reecebower98 
Please provide the config and log files and other info from the report template if you want me to be able to do anything about this - https://github.com/blipk/Customised-Workspaces/issues/new?assignees=blipk&labels=bug&template=bug_report.md&title=%5BBug%5D

This sounds like it could be related to another extension or your OS config though.

**Comment by reecebower98** [comment]
Hello, I appreciate you reaching out. I would like to provide what you
need. However I've been using Linux for only a couple years now. Could you
possibly provide commands lines and or a tutorial on retrieving these logs
for you? Sorry for the inconvenience. And for what it's worth I think your
extension is very smart.

**Comment by blipk** [comment]
Thanks @reecebower98 
Just zip up the folder at `~/.config/worksets@blipk.xyz/` and attach it to your comment here.

**Comment by blipk** [comment]
Closed due to no response and unclear issue.
