### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by yipeah** [blipk/Customised-Workspaces#36]
Hello,
Three days ago, worksets stopped working as expected on my Ubuntu 22.04. I have installed v46 (according to metadata.json) in gnome shell 42.4 and gjs 1.72.2.

None of my workspaces is shown as I defined them. All workspaces have the same appearance. Also, the worksets icon that used to be on the upper right of my screen (between keyboard layout, power and network) is not shown any more. It seems that the extension fails to start. This is confirmed in the error log after 10/9/2022 8:53;40 (see below).

Would you have an idea of how I can fix this issue? I was very happy with the extension otherwise. It does exactly what I had in mind.

Best wishes,

Kim

**Also try deleting your session configuration file and restarting (~/.config/worksets@blipk.xyz/session.json)**
(worksets@blipk.xyz) [10/6/2022, 1:35:35 PM]::Info    | cw-shell-extension.enable | @---------------------------------|
(worksets@blipk.xyz) [10/6/2022, 1:35:36 PM]::Info    | cw-shell-extension.enable | @~................................|
(worksets@blipk.xyz) [10/6/2022, 4:45:26 PM]::Info    | cw-shell-extension.disable | !~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|
(worksets@blipk.xyz) [10/6/2022, 4:45:27 PM]::Info    | cw-shell-extension.disable | !^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^|

(worksets@blipk.xyz) [10/7/2022, 2:22:41 PM]::Info    | cw-shell-extension.enable | @---------------------------------|
(worksets@blipk.xyz) [10/7/2022, 2:22:42 PM]::Info    | cw-shell-extension.enable | @~................................|
(worksets@blipk.xyz) [10/9/2022, 8:53:38 PM]::Info    | cw-shell-extension.init | @```````````````````````````````````|
(worksets@blipk.xyz) [10/9/2022, 8:53:40 PM]::Info    | cw-shell-extension.enable | @---------------------------------|
(worksets@blipk.xyz) [10/9/2022, 8:53:40 PM]:!Error   | () => | 
|-Error GSettings key only-background-details not found in schema org.gnome.shell.extensions.worksets
|-Stack Trace:
_checkKey@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:580:23
createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:532:30
_saveOptions/<@/home/kim/.local/share/gnome-shell/extensions/worksets@blipk.xyz/sessionManager.js:183:29
value/<@/home/kim/.local/share/gnome-shell/extensions/worksets@blipk.xyz/utils.js:81:22
value@/home/kim/.local/share/gnome-shell/extensions/worksets@blipk.xyz/utils.js:77:30
_saveOptions@/home/kim/.local/share/gnome-shell/extensions/worksets@blipk.xyz/sessionManager.js:181:36
saveSession@/home/kim/.local/share/gnome-shell/extensions/worksets@blipk.xyz/sessionManager.js:275:14
_cleanWorksets@/home/kim/.local/share/gnome-shell/extensions/worksets@blipk.xyz/sessionManager.js:260:14
_setup@/home/kim/.local/share/gnome-shell/extensions/worksets@blipk.xyz/sessionManager.js:201:18
SessionManager@/home/kim/.local/share/gnome-shell/extensions/worksets@blipk.xyz/sessionManager.js:67:18
enable@/home/kim/.local/share/gnome-shell/extensions/worksets@blipk.xyz/extension.js:83:18
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:183:32
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:384:26
_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:640:18
collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:28
_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:615:19
_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:646:18
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:666:14
init@resource:///org/gnome/shell/ui/extensionSystem.js:56:14
_initializeUI@resource:///org/gnome/shell/ui/main.js:298:22
start@resource:///org/gnome/shell/ui/main.js:175:5
@resource:///org/gnome/shell/ui/init.js:6:17

(worksets@blipk.xyz) [10/9/2022, 8:53:40 PM]:!Error   | () => | 
|-Error GSettings key only-background-details not found in schema org.gnome.shell.extensions.worksets
|-Stack Trace:
_checkKey@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:580:23
createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:532:30
_saveOptions/<@/home/kim/.local/share/gnome-shell/extensions/worksets@blipk.xyz/sessionManager.js:183:29
value/<@/home/kim/.local/share/gnome-shell/extensions/worksets@blipk.xyz/utils.js:81:22
value@/home/kim/.local/share/gnome-shell/extensions/worksets@blipk.xyz/utils.js:77:30
_saveOptions@/home/kim/.local/share/gnome-shell/extensions/worksets@blipk.xyz/sessionManager.js:181:36
_initOptions@/home/kim/.local/share/gnome-shell/extensions/worksets@blipk.xyz/sessionManager.js:178:14
_setup@/home/kim/.local/share/gnome-shell/extensions/worksets@blipk.xyz/sessionManager.js:203:18
SessionManager@/home/kim/.local/share/gnome-shell/extensions/worksets@blipk.xyz/sessionManager.js:67:18
enable@/home/kim/.local/share/gnome-shell/extensions/worksets@blipk.xyz/extension.js:83:18
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:183:32
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:384:26
_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:640:18
collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:28
_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:615:19
_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:646:18
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:666:14
init@resource:///org/gnome/shell/ui/extensionSystem.js:56:14
_initializeUI@resource:///org/gnome/shell/ui/main.js:298:22
start@resource:///org/gnome/shell/ui/main.js:175:5
@resource:///org/gnome/shell/ui/init.js:6:17

**Comment by blipk** [comment]
Thanks for providing the debug log @yipeah, for some reason, most people can't seem to figure that out.

I made some changes to the gsettings key names, I didn't consider the old ones will cause problems.

For a quick fix you can delete the following line from the settings section in your session.json file and restart your gnome-shell WM:
```
  "onlyBackgroundDetails": false,
```

I will update a change to fix this shortly, it takes a few days to get approved on the extension store, or you can use the updated ZIP here on git tomorrow.

**Comment by yipeah** [comment]
Hi blipk, your workaround worked. Thank you very much for your quick reply and suggestion. yipeah
