### ISSUE TITLE
[Bug] Failed to load metadata.json 'Permission Denied'

### ISSUE THREAD

**Issue by rockycruz** [blipk/Customised-Workspaces#37]
I tried to install the extension on /usr/share/gnome-shell/extensions but I'm having this error message when I checked 'journalctl /usr/bin/gnome-shell' 

![image](https://user-images.githubusercontent.com/106107226/200911972-be66ff9e-42bc-4e41-98e1-f8035630b573.png)

gnome-shell version: 3.32

Tried extension version
Shell: 3.32
Extension: 30

**Comment by blipk** [comment]
This isn't an issue with this extension, it's just how gnome and linux permissions work.

User extensions aren't designed to be installed in `/usr/share/gnome-shell/extensions` they should be in `~/.local/share/gnome-shell/extensions`

I'd suggest you install it from the extensions website or to your local directory.

If you really want to run it from the global extensions directory you will need to use `chmod` to give the correct permissions for the directory and files.

**Comment by rockycruz** [comment]
Understood. I was able to install it to /usr/share/gnome-shell/extensions and got this new error.
![image](https://user-images.githubusercontent.com/106107226/200965604-d01ee117-e213-46a3-aadf-ee172dd9fce3.png)
