### ISSUE TITLE
[Bug] GObject.registerClass() used with invalid base class (is ModalDialog)

### ISSUE THREAD

**Issue by rockycruz** [blipk/Customised-Workspaces#38]
Gnome shell: 3.32.2
![image](https://user-images.githubusercontent.com/106107226/200968819-72ffe225-bf1e-44c4-bce2-e5be1427a88d.png)

**Comment by blipk** [comment]
Hi @rockycruz 

Also says missing extension.js in your other post, so I think you've done something wrong with the installation.

Honestly these are very old versions of the extension and gnome-shell, and there was a few bugs and gnome was changing a lot during those version numbers so I can't guarantee anything and have no way to debug this.

I'd suggest trying another version of the extension, or upgrading your system.

Sorry, but closing this as something I won't/can't fix.

**Comment by rockycruz** [comment]
Got it. thanks!
