### ISSUE TITLE
[Bug] No options appear - cannot customize

### ISSUE THREAD

**Issue by happycoffeebean** [blipk/Customised-Workspaces#39]
### Desktop:
 - Gnome-Shell Version (gnome-shell --version): 42.3.1
 - GJS Version (gjs --version): 1.72.2
 - Extension Version [e.g. 22]: 
 - Linux distribution and version:  Pop_OS 22.04 LTS

### Describe the bug
Followed the directions for install.  Initially, I could see a "gear" symbol to access settings for each desktop.  I clicked it, it disappeared.  The only thing that shows is the horizontal desktop selector, and the separate desktops, but they cannot be customized.  I've attempted the reproduction steps 1-6 at least 4 times.

**To Reproduce**
1. cd ~/.local/share/gnome-shell
2. git clone https://github.com/blipk/Customised-Workspaces.git extensions
3. chmod +x install.sh && ./install.sh
4. Click "Workspaces" in main title window, see workspaces, but no customization options.
5. Open Gnome Extensions app, after third time, extension name does not appear.  
6. Deleted ~/.local/share/gnome-shell/extensions and repeated above.
7. Performed OS update, powered off completely, repeated steps 1-5.
8. Deleted .config directory after attaching debug log, followed steps 1-5 again. Same results.

**Expected behavior**
Workspaces to appear with some customization tool.  The extension to appear in the Gnome Extensions app. 

**Screenshots**
I cannot seem to grab a screenshot of the interim state - it only takes a full window. 
[debug.log](https://github.com/blipk/Customised-Workspaces/files/10027148/debug.log)

**Comment by blipk** [comment]
Hi @happycoffeebean 

I'm not really sure what you mean by the "main title window" in step 4, could you explain? Do you mean the panel / top bar?

I can see from the log file you attached that you changed some settings from the panel indicator, but then you deleted the custom workspaces from there, which caused a unhandled bug as there should be at least one (I should add in some code to prevent deleting the last one)

In any case, it should regenerate a default one from your environment once you have deleted your session file in the config directory and restarted/relogin gnome-shell.

I'm not really sure what you're exact issue is, you should be able to change the light or dark mode backgrounds as well as add any favourite apps from within that menu, and change workspace isolation options, and I can see you were able to access that.

Changes you make in gnome-shell to the backgrounds and favourites are also reflected there and it's generally the preferred way to change them.

Could you try to install the extension from the gnome extensions website instead? The install script has not been tested much, although it should work.

It may also be helpful if you can provide a screencast to properly explain what you're exact issue is. (Ctrl + Alt + Shift + R)

**Comment by blipk** [comment]
Closing due to unclear issue and no response.
