### ISSUE TITLE
nothing appears on 3.32

### ISSUE THREAD

**Issue by DevAlien** [blipk/Customised-Workspaces#4]
Unfortunately nothing appears on 3.32, maybe I missed something myself

**Comment by DevAlien** [comment]
```
|-ReferenceError Meta is not defined
```
This is the error I found, not sure how I can make that dependency to work

**Comment by DevAlien** [comment]
After that I still got many issues, so probably not ready for 3.32

**Comment by blipk** [comment]
I am currently updating the extension if you are still interested and can send me a log file for testing.

**Comment by blipk** [comment]
This should be resolved. 
There are logs in ~/.config/worksets@blipk.xyz if you are still having issues.
