### ISSUE TITLE
[Bug] Activating app grid view by using gestures, rather than shortcuts, does not show custom desktops

### ISSUE THREAD

**Issue by astatide** [blipk/Customised-Workspaces#40]
### Desktop:
 - Gnome-Shell Version (gnome-shell --version): GNOME Shell 43.1
 - GJS Version (gjs --version): gjs 1.74.1
 - Extension Version [e.g. 22]: from main; latest.
 - Linux distribution and version: Arch Linux, fully updated as of Friday, December 2nd, 2022.

### Describe the bug
On wayland (unsure about X with the gesture swipe extension, but probably there too) reaching the appgrid view using gestures (double swipe up) does not display any customized backgrounds.  Activating the app grid directly (such as by hitting the "Show Applications" button or shortcut) does show the customized backgrounds.

I played around and tried to see if it was as simple as maybe a missing signal (connecting to when the appgrid view gesture starts?  No idea what that is), but unfortunately I really don't know the internals of Gnome very well : (

**To Reproduce**
1. Login to Wayland session
2. Using trackpad gestures, double swipe to view app grid.
3. ???
4. profit! (erm, witness that all the backgrounds are the 'current' one)

**Expected behavior**
As the gesture starts, moves, and ends, the backgrounds/workspaces should remain consistent.

[debug-nogestures.log](https://github.com/blipk/Customised-Workspaces/files/10147178/debug-nogestures.log)

**Comment by blipk** [comment]
Hi @astatide 

Thanks for the report, can confirm this behaviour.

The code that controls this is in `workspaceView.js` of this extension - however it's very messy and hacky as gnome was changing the overview a lot while I was developing this.

Not sure when I'll be able to revisit this, would need to look through the gnome-shell source and find the different container for those thumbnails and update correctly (https://gitlab.gnome.org/GNOME/gnome-shell/-/tree/main/js/ui)

**Comment by astatide** [comment]
Whoa!  Holy cripes, that was fast.  Awesome!  Hah.  Thanks!

**Comment by blipk** [comment]
Yeah, I had to fix some other bugs that were annoying me with the overview stuff too, just pushed another change that finalizes all of those and the gesture stuff.

Was a little tricky to find the correct signal/function but once I did could just splice in a call to my update functions.

Hopefully gnome doesn't change too much of the overview again in the next few versions.
