### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by rclabough** [blipk/Customised-Workspaces#41]
**Is your feature request related to a problem? Please describe.**
I think it would be great if we could choose a directory of images for a workspace.  Then it could either randomly or alphabetically choose which images to show for a workspace.  For example, I have three monitors, my secondary workspace is space themed.  It would be cool to be able to switch to a secondary workspace and see random space images.

**Describe the solution you'd like**
When picking an image, have the option to also select a directory, or a range of images.  Then there could possibly be a sort/random/shuffle button that shows how you want them to be displayed.

**Comment by blipk** [comment]
Better multi-monitor support needs to be built into this code base first.

There alright might be better apps suited for this, just tick "Disable wallpaper management" in "Extension Options"

Feel free to comment back if you find anything useful or not.

**Comment by rclabough** [comment]
I've tried a few that way, the closest I got was using Desk Changer (https://github.com/BigE/desk-changer/), and they support multiple profiles, but you must select one profile statically.  You can't assign them on a per workspace level, which is why adding it to Customized Workspaces would solve a few issues there.

(Plus your UI is the cleanest and most intuitive so far)

**Comment by blipk** [comment]
I could add a flag to emit an arbitrary shell CLI command when the workspace is switched, there's already a signal for that

That way you could run desk changer to change (or a shell script to do so) to a new "static" profile whenever the custom workspace is switched.

It's quite a bit of work to implement the multi-monitor support and what you're asking, I probably won't get to it anytime soon.

**Comment by rclabough** [comment]
I like that idea, I think it's best of both worlds, adding kind of pseudo events

**Comment by blipk** [comment]
Hey @rclabough 

I added the options in a commit here: https://github.com/blipk/Customised-Workspaces/commit/a01af0639fd0594e79139f1dc413f00c0151d915

You can see the new "Workspace Switch CLI" option in the Extension Options menu.

It has an explanation in there, you can use the $CWORKSPACE variable in the command to get the name of the workspace that has just been switched to e.g.
`echo "Switched to workspace $CWORKSPACE"`

You should be able to pass that to the CLI flags of desk changer, or to a shell script to handle that: 
`bash my_script.sh $CWORKSPACE`


Please install and test the feature using the .zip file in the repo root or from the latest release here: https://github.com/blipk/Customised-Workspaces/releases

If you don't run into any problems, I will submit it for approval on the extensions marketplace.

**Comment by blipk** [comment]
Going to close this as no more responses, the implementation worked well in my testing.
