### ISSUE TITLE
New icon of "customised-workspaces" added after each unlock

### ISSUE THREAD

**Issue by yipeah** [blipk/Customised-Workspaces#42]
Hello,

I've noticed after the last update (some days ago) that now each time I unlock my screen, a new icon of customised-workspaces appears in my status bar. I have not figured out how to remove them.

Please have a look at the attached screenshot. Would you be so kind and try to find a way to prevent this behavior? Thank you very much in advance for your help and for this wonderful extension. I appreciate it a lot and use it all the time.

Best wishes,

yipeah

![Screenshot from 2023-04-06 08-24-45](https://user-images.githubusercontent.com/40759034/230291307-134de736-0fbd-4083-acbb-9721945ad2d5.png)

**Comment by blipk** [comment]
Hey, that's been fixed, you can use the release or zip in the repo, or wait a few days for the fix to be approved on the extensions site.

**Comment by yipeah** [comment]
Great! Thank you very much for your help. Best wishes, yipeah
