### ISSUE TITLE
Add support for Gnome 44

### ISSUE THREAD

**Issue by brunnogama** [blipk/Customised-Workspaces#43]
Fedora 38 has Gnome 44 default, but unfortunately has broken Customized Workspaces.

I've tried manually upping the version in the json to support 44, but it doesnt work, even the icon for configuration on top bar doesnt show.
The separate workspace only works with this extension.
Your extension is essential for me to use gnome, I really like this and a big thanx for that!

**Comment by blipk** [comment]
@brunnogama 

It would be helpful if you provided the log file and other info mentioned in the issue template.

I won't be able to provide any official release until v44 is released on Arch.

**Comment by yzx9** [comment]
Hello, Gnome 44 has been released on May 6th, can you update this extension? Isolate workspaces on Gnome is indispensable to me, thanks for maintaining it.

**Comment by blipk** [comment]
@yzx9 
I'm actually on Manjaro, and it's not here yet, hopefully within the next week.

Again it would be helpful if anyone could provide the log files and I may be able to provide a fix sooner.

**Comment by brunnogama** [comment]
@blipk Hey man!
I wanna help but I dont know how to generate log fort extensions.

**Comment by blipk** [comment]
@yzx9 

From the issue template:
## Please include the debug file from ~/.config/worksets@blipk.xyz/debug.log 

It may not be there though if the extension is not starting, but would be helpful if it is.

**Comment by yzx9** [comment]
@blipk Hey! Sorry for not noticing the issue template.

When I do the following:

1. clone the extension;
2. add `44` to the `metadata.json.shell-version`;
3. install the extension & restart gnome-shell;

Encountered error in `error.log`:

```
(worksets@blipk.xyz) [5/11/2023, 11:01:03 AM]::Info    | cw-shell-extension.init | @```````````````````````````````````|
(worksets@blipk.xyz) [5/11/2023, 11:01:03 AM]::Info    | cw-shell-extension.enable | @---------------------------------|
(worksets@blipk.xyz) [5/11/2023, 11:01:03 AM]:!Error   | cw-shell-extension.enable | 
|-TypeError Meta.MonitorManager.get is not a function
|-Stack Trace:
enable@/home/yzx9/.local/share/gnome-shell/extensions/worksets@blipk.xyz/extension.js:68:63
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:196:38
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:398:32
async*_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:677:24
async*_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:683:48
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:718:20
async*init@resource:///org/gnome/shell/ui/extensionSystem.js:59:14
_initializeUI@resource:///org/gnome/shell/ui/main.js:311:22
start@resource:///org/gnome/shell/ui/main.js:186:5
@resource:///org/gnome/shell/ui/init.js:6:17
```

**Comment by blipk** [comment]
Thanks @yzx9 
I have seen your PR as well, but implemented a fix in my preferred style.

If you are able to test and let me know if everything is working, that would be great.

**Comment by yzx9** [comment]
@blipk Yes, it works.

**Comment by yzx9** [comment]
@blipk This issue seems to be fixed but not released, can you release a new version in https://extensions.gnome.org/extension/1583/worksets/

**Comment by blipk** [comment]
@yzx9 
44 is still not available on my distro and one person just saying "it works" isn't enough for me to roll out the changes to everyone, there may be features you don't use that are broken.

**Comment by blipk** [comment]
@yzx9 
I've pushed the changes to extensions.gnome.org anyway, awaiting review: https://extensions.gnome.org/review/41925
It should be reviewed and approved by the end of the week.

You may need to delete the version you installed from github, or lower the version in the metadata.json file, to force an update after approval.

**Comment by yzx9** [comment]
> @yzx9 I've pushed the changes to extensions.gnome.org anyway, awaiting review: https://extensions.gnome.org/review/41925 It should be reviewed and approved by the end of the week.
> 
> You may need to delete the version you installed from github, or lower the version in the metadata.json file, to force an update after approval.

Thanks! New version is now actived.
