### ISSUE TITLE
[Bug] Possible Memory leak.

### ISSUE THREAD

**Issue by ChrisMidkiff** [blipk/Customised-Workspaces#45]
### Desktop:
 - Gnome-Shell Version (gnome-shell --version): 44.2
 - GJS Version (gjs --version): 1.76.2
 - Extension Version [e.g. 22]: 55
 - Linux distribution and version: Manjaro

### Describe the bug
Enabling this extension and switching workspaces increase memory usage of gnome-shell, without it being enabled gnome-shell sits at ~400MB of ram used. With it enabled and after switching workspaces a few times this usage increases to over a gigabyte and continues to increase. I've seen it as high as 6GB after a while.

**To Reproduce**
Enabling this extension and switching workspaces

**Expected behavior**
Use less memory

**Screenshots**
[debug.log](https://github.com/blipk/Customised-Workspaces/files/11908286/debug.log)

**Comment by blipk** [comment]
Yeah I'm probably not going to fix this.

The gnome teams make countless undocumented changes and have made it near impossible to debug extensions.

Latest versions of GTK seem to have broken a lot, and I can't even debug with restarting X sessions anymore.

Gnome-shell and GJS are inherently flawed with all kinds of memory leaks, can't say I've noticed your issue or had reports of memory leaks before, but it doesnt surprise me in the least.

Ideally this extension needs a complete rewrite, and it's not something I have the time for right now.

**Comment by blipk** [comment]
@ChrisMidkiff 

I've uploaded a new version with various fixes to the gnome-extensions website, it should be reviewed and approved in a few days.

Could you please try that and if you're still having the issue can you reopen the issue and provide your `session.json` and a new `debug.log` files from the config directory as well as any more information that may help me find the cause of this - as I am unable to reproduce.

Thanks
