### ISSUE TITLE
[Bug] Update to v57 breaks Customised Workspaces

### ISSUE THREAD

**Issue by THgithub19** [blipk/Customised-Workspaces#46]
### Desktop:
 - Gnome-Shell Version (gnome-shell --version): 42.5
 - GJS Version (gjs --version): 1.72.2
 - Extension Version [e.g. 22]: 57
 - Linux distribution and version: Ubuntu 22.04.2 LTS

### Describe the bug
Update from v55 to v57 of Customised Workspace extension leads to loss of customised workspaces.

**To Reproduce**
1. Update extension from v55 to v57 on the desktop mentioned above
2. Note lost panel indicator and lost workspaces and the error message in log-file:
(worksets@blipk.xyz) [13.7.2023, 12:37:28]:!Error   | () => | 
|-TypeError Me.gExtensions.dash2panel is undefined
3. Downgrade manually back to v55
4. Note panel indicator and workspaces are back again, no error message in the log-file.

**Expected behavior**
Customised Workspaces and panel indicator are present in v57 of the extension.

**Screenshots**
[debug.log](https://github.com/blipk/Customised-Workspaces/files/12039173/debug.log)

**Comment by blipk** [comment]
@THgithub19 This has been fixed in v58 which should be reviewed onto extensions.gnome.org in the next few days - alternatively you can use the release in this repo

**Comment by THgithub19** [comment]
Great, works again, thank you for your very quick fix!
