### ISSUE TITLE
Use a pre-existing workspace config for a new workspace

### ISSUE THREAD

**Issue by ChauhanT** [blipk/Customised-Workspaces#48]
**Is your feature request related to a problem? Please describe.**
I have defined a few configs (e.g., reading, browsing, coding). Suppose I am using the coding and browsing configurations. Now, I create a new workspace where I'd like to start work on a new coding project. Currently, I am unable to select the coding config because it navigates to the already open coding workspace. It would be great to have more than one open workspaces with the sames config.

**Describe the solution you'd like**
The ability to assign the same config to multiple workspaces.

**Describe alternatives you've considered**
I have not considered any other alternatives.

**Additional context**
I am happy to give more details about the feature request. Thank you, irrespective of whether you decide to implement this feature or not !

**Comment by blipk** [comment]
Hi, the easiest way to do this would be to duplicate the configs and give them a slightly different name.

Unfortunately it's not easy to implement this into the extension as the config name is used as the key to tell which workspace it is on etc.

If you want to submit a PR that would be great, but I'm not going to implement this myself.

**Comment by ChauhanT** [comment]
Got it, thanks! And do you think it might be easier to implement a button that lets the user create a copy of an existing config (maybe with a serial number appended). E.g., clicking the button for a config called 'code' would create a config 'code 2'.

**Comment by blipk** [comment]
@ChauhanT 

This extension is mostly in maintenance mode and not really adding new features.


![image](https://github.com/blipk/Customised-Workspaces/assets/45532845/10993a74-2aab-4f28-b207-7d2f7d1debf4)

You can set it up yourself though, use the top right icon to save the customised workspace

Then go to `~/.config/worksets@blipk.xyz/envbackups` and change the `WorksetName` in the `.json` file

Then use the bottom right load icon to load it.

**Comment by ChauhanT** [comment]
@blipk Sorry, didn't realise the extension was in maintenance-only mode! Thank you very much for patiently responding nonetheless :) I'll use the trick you pointed out.
