### ISSUE TITLE
[Feature Request] Add GNOME 45 Support

### ISSUE THREAD

**Issue by sanecito** [blipk/Customised-Workspaces#49]
### Desktop:
 - Gnome-Shell Version (gnome-shell --version): 45.2
 - GJS Version (gjs --version): 1.78.0
 - Extension Version [e.g. 22]: 44
 - Linux distribution and version: Fedora Linux Rawhide.20231204.n.0 (Silverblue Prerelease)

### Describe the bug
GNOME Extensions comments that "The extension is incompatible with the current GNOME version". Selecting "Settings" outputs an error. This is expected behavior as the most recent version listed on https://extensions.gnome.org/extension/1583/worksets/ is 44, not 45. However, as 45 has been out for two and a half months it should be reasonably stable to have the extension supported on 45.

GNOME 45 was released on September 20, 2023: https://release.gnome.org/45/ 

**To Reproduce**
1. Go to https://extensions.gnome.org/extension/1583/worksets/ 
2. Note that the most recent supported GNOME version is 44.

**Expected behavior**
Extension is listed for 45 on extensions.gnome.org and able to execute

**Screenshots**
Error output:

The settings of extension worksets@blipk.xyz had an error:
```
SyntaxError: import declarations may only appear at top level of a module
```

Stack trace:
```
@file:///var/home/[user]/.local/share/gnome-shell/extensions/worksets@blipk.xyz/prefs.js:29:28
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

**Comment by blipk** [comment]
I might get around to it eventually, or someone can submit a PR.

**Comment by blipk** [comment]
Actually I don't like your attitude.

"However, as 45 has been out for two and a half months it should be reasonably stable to have the extension supported on 45."

What bullshit. I've spent countless hours on this without so much a thanks, and everyone who posts an issue is so corporate and demanding.

Someone can submit a PR if they want support.

**Comment by sanecito** [comment]
> Actually I don't like your attitude.
> 
> "However, as 45 has been out for two and a half months it should be reasonably stable to have the extension supported on 45."

This was a comment on how often folk will suggest for upgrades to let it sit between a week or until the first point release. Arch/Manjaro can be temperamental, so if you were seeing some issue on your system testing following the GNOME 45 release and were waiting for upstream, GNOME 45, to be more stable I was commenting that hopefully whatever issues you might have seen are patched upstream to allow for Customized Workspace to be released for GNOME 45. It wasn't a comment on your capacity as a developer or seeking to demean your work that allowed GNOME Shell to have a feature KDE's Plasma includes.

**Comment by blipk** [comment]
It's no problem @sanecito, just a misunderstanding.

There are a lot of changes to the extension system in gnome-shell 45, I don't use this extension myself anymore, and I don't really have the inclination to update it for the changes.

A PR is welcomed, or I may consider archiving this repository eventually.

**Comment by blipk** [comment]
Hey @sanecito 

I've updated everything for gnome 45, if you're still interested it would be good if you could use the preview .zip from this repo and give it a test.

Report any issues and any errors in the debug file: `~/.config/worksets@blipk.xyz/debug.log
