### ISSUE TITLE
Can't get it to work on Gnome Shell 3.34.3

### ISSUE THREAD

**Issue by Philipp0205** [blipk/Customised-Workspaces#5]
The extensions looks great! 
I tried to install it today on Ubuntu 19.10 with GNOME Shell 3.34.3. Everything seems to install fine but the "+" icon does not appear. 

Any hints?

**Comment by blipk** [comment]
Hey @Philipp0205 there should be a debug.log file in ~/.config/worksets@blipk.xyz
Could you please upload that for me.

**Comment by blipk** [comment]
Also note: the latest version has not been released on the gnome extensions website yet, if you are using the package from there it is outdated.

**Comment by blipk** [comment]
Hey @Philipp0205 the latest version has now been reviewed and published here: https://extensions.gnome.org/extension/1583/worksets/

Can you please let me know if you are still having issues.

**Comment by blipk** [comment]
No updates.
