### ISSUE TITLE
[PR Request] Gnome Shell 45 support

### ISSUE THREAD

**Issue by blipk** [blipk/Customised-Workspaces#50]
There are a lot of changes to the extension system in gnome-shell 45, I don't use this extension myself anymore, and I don't really have the inclination to update it for the changes.

If there are still people using this extension, someone will have to look into the changes and submit a suitable PR.
(see https://gjs.guide/extensions/upgrading/gnome-shell-45.html)

Otherwise I may consider archiving this repository eventually if I continue not to use it.

Thanks for everyone who has used this extension, and the one user who donated me some EUR that paypal stole.

**Comment by Iamrsanchez72** [comment]
I actually adore this extension - and may take a pass at updating it myself.  I'd been hoping and watching to see if you'd be updating it, but will take a pass at it myself.

**Comment by blipk** [comment]
@Iamrsanchez72 

I have updated the code so it should be working with Gnome 45.

It would be good if someone could test it, you can use the .zip file in this repo.

**Comment by blipk** [comment]
Marking this as completed, as it will be released to extensions.gnome.org soon, if there are any problems please open a new issue.
