### ISSUE TITLE
[Bug] broken on Gnome 45

### ISSUE THREAD

**Issue by FarisZR** [blipk/Customised-Workspaces#51]
## Please include the debug file from ~/.config/worksets@blipk.xyz/debug.log and fill out the following sections
[debug.log](https://github.com/blipk/Customised-Workspaces/files/14322846/debug.log)

### Desktop:
 - Gnome-Shell Version (gnome-shell --version):
 45.4
 - GJS Version (gjs --version):
 gjs 1.78.3
 - Extension Version [e.g. 22]:
 63
 - Linux distribution and version:
Fedora 39

### Describe the bug
I can't customize anything related to the workspaces, the submenus don't show up when clicking on any workspace.

**To Reproduce**
1. Install on Gnome 45
2. Click on any workspace.

**Expected behavior**
it should work and show options to customize the wallpaper and the available apps.

**Screenshots**
[video.webm](https://github.com/blipk/Customised-Workspaces/assets/35614734/9e2784e9-5b5d-460d-8837-3a28430269a2)

**Comment by blipk** [comment]
@FarisZR 

Are you using an old `session.json` file? It looks like it might contain URI's to background files that are no longer existing.

Can you try deleting ~/.config/worksets@blipk.xyz/session.json and report if that solves the issue.

**Comment by FarisZR** [comment]
Just tried that, still facing the same issue.

-------- Ursprüngliche Nachricht --------
Am 18.02.24 23:11 um K - notifications at github.com schrieb :

**Comment by blipk** [comment]
Ah okay.

Well I'm not getting the full error log there, I had to change a lot for v45 and it looks like my logging function got a bit broken.

I pushed a change to this repo that should fix that, could you try that (extract the .zip) and upload a new debug.log after trying to open the extension menu aagain?

Or alternatively you could find the full error stack trace in gnome-logs and paste that here.

**Comment by blipk** [comment]
@FarisZR 

The fixed debugging has been reviewed on extensions.gnome.org and you should get that update automatically.

I will need a new debug.log file after updating if you want this resolved.

**Comment by blipk** [comment]
> Just tried that, still facing the same issue.

Did you restart the shell after?

**Comment by FarisZR** [comment]
I restarted the whole system since then, here is a new debug.log file
[debug.log](https://github.com/blipk/Customised-Workspaces/files/14362423/debug.log)

**Comment by blipk** [comment]
@FarisZR 

I can see your background is set to an XML file: `/usr/share/backgrounds/f33/default/f33.xml`

Customised-Workspaces does not support this, if you delete this string from `~/.config/worksets@blipk.xyz/session.json` then restart you should work.

Later I will update the code so it does not save those XML files.

**Comment by blipk** [comment]
@FarisZR 

Should be fixed with an update from the Extensions app soon

**Comment by blipk** [comment]
Closing as should be fixed with an update. Please reopen with a new debug.log if the issue persists.
