### ISSUE TITLE
[Feature] Gnome (46) New Version Support Requests

### ISSUE THREAD

**Issue by forabi-cosuno** [blipk/Customised-Workspaces#52]

**Comment by blipk** [comment]
All support requests will have to wait until the new Gnome version is released on Manjaro/Arch and then additional time for the extension to be updated.

Unless you're willing to provide debug files, test changes and possibly contribute, then please be patient.

**Comment by blipk** [comment]
Gnome 46 release awaiting approval on extensions.gnome.org

**Comment by forabi** [comment]
Can we repurpose this issue for Gnome 47 support?
