### ISSUE TITLE
Squared workspace's corners in overview

### ISSUE THREAD

**Issue by JeanValjean30** [blipk/Customised-Workspaces#54]
# Desktop:
 - Gnome-Shell version: 42.9
 - GJS version: 1.72.2
 - Extension version: 60
 - Linux distribution and version: Ubuntu 22.04

# Describe the bug
In the overview, the workspace's corners are rounded but become squared after swipping to the previous or the next one. The "trasformation" occurs with and without other esthetic extensions like "Just perfection" and "Blur my shell".

# Reproduce
1. Go to the top right corner 
2. Click on activities
3. Swipe left or right

# Expected behavior
Workspaces's corner always rounded

# Screenshots
![Schermata del 2024-05-04 16-05-24](https://github.com/blipk/Customised-Workspaces/assets/168914674/aa581d9f-358a-4ec7-a6e2-b8d7c4f2b134)
[debug.log](https://github.com/blipk/Customised-Workspaces/files/15209908/debug.log)

**Comment by blipk** [comment]
@JeanValjean30 

I'm unable to reproduce this on the latest versions.

You're using a rather old version of the extension and gnome-shell, and the extensions site doesn't allow me to update for previous versions anyway.

Please upgrade to latest versions and re-open if the problem persists.
