### ISSUE TITLE
[Bug] In Gnome 46 the extension breaks the look of the top-right menu

### ISSUE THREAD

**Issue by dominalien** [blipk/Customised-Workspaces#55]
### Desktop:
 - Gnome-Shell Version (gnome-shell --version): 46.4
 - GJS Version (gjs --version): 1.80.2
 - Extension Version [e.g. 22]: 68
 - Linux distribution and version: Fedora 40

### Describe the bug
Enabling the extension breaks the look of the top-right Gnome menu.

**To Reproduce**
1. Click on the top-right menu (wifi, volume, battery)
2. See the menu look broken

**Expected behavior**
The top-right menu looks the same with extension on and off

**Screenshots**
Extension off:

![Zrzut ekranu z 2024-08-16 16-43-40](https://github.com/user-attachments/assets/b4221dd5-e50e-47e9-8c9f-74072c8c0c7c)

Extension on:
![Zrzut ekranu z 2024-08-16 16-41-45](https://github.com/user-attachments/assets/1ecff434-5551-42fe-b22c-902cc85b6724)
[debug.log](https://github.com/user-attachments/files/16638458/debug.log)

**Comment by blipk** [comment]
Look like back in gnome-shell v43 they decided to choose a CSS class name that I was already using, and also for some reason they decided that extension CSS files would apply globally without any configuration for that.

Have pushed the fix to the repo and extensions.gnome but will take a few days for approval there.

**Comment by dominalien** [comment]
I just got the extension update. It's all fixed, thank you for your super-speedy response. :-)

**Comment by dominalien** [comment]
Whaaa, that blows my tiny little mind.

I am this |-| close to ditching Gnome, your extension will surely keep me here longer. :-)

**Comment by blipk** [comment]
Thanks for the support @dominalien 
I really appreciate it
