### ISSUE TITLE
[Bug] Switching workspaces is jerky and slow

### ISSUE THREAD

**Issue by dominalien** [blipk/Customised-Workspaces#56]
### Desktop:
 - Gnome-Shell Version (gnome-shell --version): 46.4
 - GJS Version (gjs --version): 1.80.2
 - Extension Version [e.g. 22]: 68
 - Linux distribution and version: Fedora 40

The machine is a laptop with Ryzen 5 3500U and Radeon Vega 8 Graphics.

### Describe the bug
With the extension activated, switching workspaces is sometimes ok, but mostly it gets a delay and drops frames, to the point the new workspace will appear with no animation after a second or two.

Disabling the extension makes workspace switching fast and smooth again.

**To Reproduce**
1. Press the super key
2. Move the mouse wheel up and down a few times
3. Workspace switching is slow, frames get dropped, new workspace appears with a delay

**Expected behavior**
Retain the smoothness and speed of switching workspaces without the extension
[debug.log](https://github.com/user-attachments/files/16638685/debug.log)

**Comment by blipk** [comment]
Yeah this seems to change from version to version of gnome-shell, there's some repeat rendering in the extension due to changing of signals etc.

I will look into it if I ever get the time/motivation.

Or if anyone wants to the functions are in `workspaceManager.js`

**Comment by blipk** [comment]
Ok I did some profiling and it seems the re-renders don't really matter much and the slowest functions are actually in `sessionManager.js`: 
 `sessionManager.setFavorites()` and `sessionManager.setBackground()`


```
(worksets@blipk.xyz) [17/08/2024, 4:54:49 pm]:-> sessionManager.js:542:17 -> dev.js:43:12
:INFO   |  Timer 'setFavorites' took 102.053ms
(worksets@blipk.xyz) [17/08/2024, 4:54:49 pm]:-> sessionManager.js:550:17 -> dev.js:43:12
:INFO   |  Timer 'setBackground' took 39.113ms
(worksets@blipk.xyz) [17/08/2024, 4:54:49 pm]:-> sessionManager.js:554:17 -> dev.js:43:12
:INFO   |  Timer 'displayWorkset' took 149.079ms
```

`setFavorites` is actually taking the most time but all it's doing is setting the dconf setting "favorite-apps"

So it's actually something in gnome-shells source code that is taking too long to do that, probably one of the functions hooked into the signal for when that changes: https://gitlab.gnome.org/search?search=favorite-apps&nav_source=navbar&project_id=546&group_id=8&search_code=true&repository_ref=main


`setBackground` is probably a similar story, although some of my code could maybe be improved, it's not nearly as slow as `setFavorites` though.

**Comment by dominalien** [comment]
Thank you very much for taking the time to do all this. :-)

I didn't want to clutter the bug report, but the extension is awesome and very useful and I love it, slow animations and all.

So it looks like this is something Gnome devs will have to tackle?

**Comment by blipk** [comment]
Yeah I just noticed that the isolater is not working either...

It was in the last version of gnome-shell, it seems to break a lot.
I will look into getting that fixed too.

**Comment by blipk** [comment]
@dominalien 

Do you have dash-to-panel or dash-to-dock installed?

**Comment by dominalien** [comment]
No.

I have enabled: AppIndicator and KStatusNotifierItem Support installed (this one is installed by default as an rpm), Another Window Session Manager, Battery Health Charging, Caffeine and Clipboard Indicator.

I have some other extensions installed, but not enabled.

**Comment by blipk** [comment]
@dominalien 

Yes, I was asking installed but not enabled.

My code checks for dash-to-panel or dash-to-dock and defers to their isolation features if available, however I was only checking if they were installed, not enabled.

I've fixed to check both now and the isolater is working for me when I disable dash-to-panel.


I've also spent far too long profiling the functions in my code and in gnome-shells code, I managed to cut the timing down about 40% (~150ms down to ~80ms) and it is a little smoother.

Although it really should be 10ms at the longest and even that is a lot, but most of it is actually coming from the gnome-shell code @ `appDisplay.AppDisplay._redisplay` and there's not a whole lot I can do about that.


I'm going to submit these changes to extensions.gnome.org but it was quite a few more changes than the last update so will probably take longer to review, and possibly will be rejected initially as the reviewer there is kind of annoying.

You can try the .zip file in the repo for now - but remember to delete it later as it will prevent any updates from the extensions website.

**Comment by blipk** [comment]
Also closing this for now as I probably won't work on this anymore for now, feel free to open again a few months after the next gnome-shell version is released and I will have a look again if it's still a problem.

**Comment by dominalien** [comment]
Awesome, thank you. I'll be sure to note how it works when Fedora updates and will get back to you then.

**Comment by drzraf** [comment]
One of the main blocker for me! I wanted to rely on it for get per-desktop background ¹, but the feature induce an unacceptable 1-2 seconds delay when switching.

¹ Something that used to work out of the box ten years ago.

**Comment by oktayacikalin** [comment]
You should reopen it for gnome 47. It's slow and jerky again. Setting the favorites could be delayed - the background is more important in timing. Isolation is also slowing it down.

I was trying to use it along PaperWM but it's just too slow.

**Comment by blipk** [comment]
@drzraf 
@oktayacikalin 

As per my previous comment, most of the delay is in gnome-shell code that can't be changed, it's just a side effect of the modifications this extension needs.

Although there are improvements that could also be made to the extension code, I don't really have the time nor motivation to refactor it to something more performant.

I would welcome any PR's that refactor the code and/or convert to typescript.
