### ISSUE TITLE
UI suggestions

### ISSUE THREAD

**Issue by FreeTheSmoke** [blipk/Customised-Workspaces#8]
Amazing extension, I'm listing some things here that I think would make it even better. I'm happy to try and help but I cant really code :facepalm:

[ ] The light grey text for entry of "Name of new environment" is quite hard to read.

[ ] There are times when a person might be a rush to get one (or fifteen) things done quickly, at those times a minimum of required inputs usually makes for the most enjoyable use - While its really nice to enter custom descriptions it would be great if some sort of default like "WorkSpace_1, ...2, etc" (or 20200609-2351) would be entered in the text field already, and the "done" box selected, so a first-time user or person in a rush could just hit Enter.

[ ] We have the entire height of the screen to work with, so while its good that a scroll bar is available once I click to edit an environment, maybe the menu should first grow longer automatically (at least until 75% of screen-height)

[ ] "tooltips" for hovering over the buttons would be great, failing that maybe shorten toggle button text  "isolate running applications" to "isolate running apps" then there would be room at the top left to add a "?" button {see image 1} that directs to [https://raw.githubusercontent.com/blipk/Customised-Workspaces/master/doc/CustomisedWorkspacesUserInterfaceGuide.png](url)

[ ] Clicking "Close Active" doesn't appear to have any affect if you are currently on a WorkSpace that references that environment (although it updates when you leave) maybe the user should be notified that "environment for the current workspace will be updated when you change to another" like the nice toast mesg that is used when a new environment is created.

[ ] Minor one, but if I have 3 environments set up, and I expand the top one in the menu, the second environment gets included in the scrolling bit, now if expand the lowest environment it gets it's own scroll bar? - {see image 2}

[ ] Names are checked for collisions at time of saving, but only against currently loaded environments. It is possible to end up with multiple identically named profiles...maybe it should check the backups filenames too and at least warn the user? - {see image 3}

![UI1_WorkSpaces](https://user-images.githubusercontent.com/38685664/81477408-0b733400-925b-11ea-9d21-39eff7113990.png)
![UI2_WorkSpace](https://user-images.githubusercontent.com/38685664/81477430-2180f480-925b-11ea-96e6-71edca9bc392.png)
![UI3_WorkSpaces](https://user-images.githubusercontent.com/38685664/81477439-29409900-925b-11ea-9b7e-3e239fe138de.png)

**Comment by blipk** [comment]
```
[ ] The light grey text for entry of "Name of new environment" is quite hard to read.

[ ] There are times when a person might be a rush to get one (or fifteen) things done quickly, at those times a minimum of required inputs usually makes for the most enjoyable use - While its really nice to enter custom descriptions it would be great if some sort of default like "WorkSpace_1, ...2, etc" (or 20200609-2351) would be entered in the text field already, and the "done" box selected, so a first-time user or person in a rush could just hit Enter.
```
Thanks for the suggestions, this has now been implemented in the latest releases here.

```
[ ] We have the entire height of the screen to work with, so while its good that a scroll bar is available once I click to edit an environment, maybe the menu should first grow longer automatically (at least until 75% of screen-height)

[ ] Minor one, but if I have 3 environments set up, and I expand the top one in the menu, the second environment gets included in the scrolling bit, now if expand the lowest environment it gets it's own scroll bar? - {see image 2}
```
I have changed the height, you can increase `.ci-history-menu-section` in stylesheet.css if you need it higher.
There are actually two scrolling sections, both limited by the height there, one for the 'Favourited/Starred' and one for those that are not, the two sections is how the starred ones are maintained at the top of the list.

I'm thinking of removing the starring functionality and just having the active environments in the uppermost section.


```
[ ] "tooltips" for hovering over the buttons would be great, failing that maybe shorten toggle button text "isolate running applications" to "isolate running apps" then there would be room at the top left to add a "?" button {see image 1} that directs to https://raw.githubusercontent.com/blipk/Customised-Workspaces/master/doc/CustomisedWorkspacesUserInterfaceGuide.png
```
I'm not sure if tooltips are doable, I will look into it. I have made some UI design changes, but the ? popup is a good idea and I know how I can implement that.


```
[ ] Clicking "Close Active" doesn't appear to have any affect if you are currently on a WorkSpace that references that environment (although it updates when you leave) maybe the user should be notified that "environment for the current workspace will be updated when you change to another" like the nice toast mesg that is used when a new environment is created.
```
The 'close active' is really just so you can close an auto-loaded environment if you'd like to a load a different one than usual on the workspace.
When closing it, there's not really indication on what to change the background/favourites back to, so it's just waiting until another environment is loaded.
Perhaps being able to mark a single Environment as 'default' and having that be loaded in the case of nothing else? or if you would suggest something else?

```
[ ] Names are checked for collisions at time of saving, but only against currently loaded environments. It is possible to end up with multiple identically named profiles...maybe it should check the backups filenames too and at least warn the user? - {see image 3}

Are those environments actually 'loaded' into the session? or are they backups from ones you have deleted?

These are seperate from the ones loaded in the session, they are stored here if you want to delete them: ~/.config/worksets@blipk.xyz/envbackups

It does get quite messy to look at though, I will look at grouping them by name and then being able to select them by date, if its not too much to implement. Otherwise it may be easier to just have a delete button in the UI there to delete the backup files as well.


Let me know how you go with the latest update here, the zip file in the root directory has everything.

**Comment by blipk** [comment]
Have now added information 'tooltips' explaining what buttons/options do when hovering over them

**Comment by blipk** [comment]
Everything has now been implemented except for managing the backups.

Still need to tweak the tooltip code a little too.

**Comment by blipk** [comment]
Tooltip code has been tweaked, and there is now a button in the backups to open the folder and manage them directly.

Closing off this issue, although feel free to open another one in regards to any of the changes I've made.
